config/routes.rb
Rails.application.routes.draw do
	root 'index#index'

	match '/new_collection',						to: 'index#new_collection',			  	via: 'get'
	match '/save_collection',						to: 'index#save_collection',		  	via: 'post'
	match '/search_query',						    to: 'index#search_query',		  		via: 'post'
end

app/models/collections.rb
class Collections < ActiveRecord::Base
end

app/models/document_url_maps.rb
class DocumentUrlMaps < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

	def index
		@collections = Collections.all
	end

	def new_collection
		@collection = Collections.new
	end

	def save_collection
		command = "java -classpath #{Rails.root}/java/custom-wse.jar wse.CreateCorpus -url " + params[:collections][:seed_url] + " -depth " + params[:collections][:max_depth] + " -pages " + params[:collections][:max_pages]
		output = `#{command}`

		latest_log_file_saved = Dir.glob("/home/arcelik/git/custom_web_search_engine_server/data/logs/*.log").max_by {|f| File.mtime(f)}
		collection_id = latest_log_file_saved.split("/logs/")[1].split(".")[0].to_i
		number_of_pages_retrieved = Dir["/home/arcelik/git/custom_web_search_engine_server/data/collections/"+ collection_id.to_s + "/*"].length
		
		collection = Collections.new(collection_params)
		collection.save()
		collection.update_attribute(:no_of_pages_retrieved, number_of_pages_retrieved)
		collection.update_attribute(:collection_id,collection_id)

		map_file = File.open("/home/arcelik/git/custom_web_search_engine_server/data/logs/" + collection_id.to_s + ".url.map").read
		map_file = map_file.split("\n")
		map_file.each do |line|
			line = line.split("\t")
			document_url_map = DocumentUrlMaps.new(:collection_id => collection_id, :document_id => line[0].to_i, :url => line[1])
			document_url_map.save
		end
		redirect_to root_path
	end

	def search_query
		@query = params[:query]
		collection_id = Collections.find_by_id(params[:collection_id_field].to_i).collection_id
		@results = []
		if not params[:mmr]
			if params[:wand]
				command = "java -classpath #{Rails.root}/java/custom-wse.jar wse.SearchQuery -query " + params[:query] + " -cid " + collection_id.to_s + " -w"
			else
				command = "java -classpath #{Rails.root}/java/custom-wse.jar wse.SearchQuery -query " + params[:query] + " -cid " + collection_id.to_s
			end
			output = `#{command}`
			output.split(" ").each do |o|
				doc_url_map = DocumentUrlMaps.where(:collection_id => collection_id,:document_id=>o.to_i)
				@results.push(doc_url_map.first.url)
			end
		else
			if params[:wand]
				command = "java -classpath #{Rails.root}/java/custom-wse.jar wse.SearchQuery -query " + params[:query] + " -cid " + collection_id.to_s + " -k 20 -w"
			else
				command = "java -classpath #{Rails.root}/java/custom-wse.jar wse.SearchQuery -query " + params[:query] + " -cid " + collection_id.to_s + " -k 20"
			end
			output = `#{command}`

			mmr_input_directory_name = "#{Rails.root}/data/mmr_input"
			Dir.mkdir(mmr_input_directory_name) unless File.exists?(mmr_input_directory_name)
			mmr_output_directory_name = "#{Rails.root}/data/mmr_output"
			Dir.mkdir(mmr_output_directory_name) unless File.exists?(mmr_output_directory_name)
			
			output.split(" ").each do |in_res|
				file_name = "#{Rails.root}/data/collections/" + collection_id.to_s + "/" + in_res
				# puts file_name
				FileUtils.cp file_name, mmr_input_directory_name
			end

			Dir.chdir "#{Rails.root}/java/mmr/"
			command = "#{Rails.root}/java/mmr/./run TestDiversity " + mmr_input_directory_name + " " + mmr_output_directory_name + " '" + params[:query] + "'"
			output = `#{command}`
			Dir.chdir "#{Rails.root}"
			FileUtils.rm_r mmr_input_directory_name
			FileUtils.rm_r mmr_output_directory_name
			output.split("\n").each do |o|
				doc_url_map = DocumentUrlMaps.where(:collection_id => collection_id,:document_id=>o.to_i)
				@results.push(doc_url_map.first.url)
			end

			# /home/arcelik/git/custom_web_search_engine_server/java/mmr/./run TestDiversity 
			# /home/arcelik/git/custom_web_search_engine_server/data/directory_for_mmr 
			# /home/arcelik/git/custom_web_search_engine_server/data/directory_for_mmr_results/ 'solay system'


			# @results = initial_results

		end
	end

	private
	def collection_params
		params.require(:collections).permit(:seed_url, :max_depth, :max_pages)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/index/index.html.erb
<script type="text/javascript">
	function myFunction() {
		
		var radio_buttons = document.getElementsByName('selected_collection[collection_id]')
		for (var i = 0; i < radio_buttons.length; i++) {
			if (radio_buttons[i].checked) {
				document.getElementById('collection_id_field').value = radio_buttons[i].value;
				return true;
			}
		}
		alert("You need to select a collection to search");
    	return false;
	}
</script>


<h2> Available Collections </h2>
<br>

<%= form_tag search_query_path do %>

	<%= text_field_tag :query %>
	<%= hidden_field_tag :collection_id_field %>
	<%= submit_tag "Search", :onclick => "return myFunction()" %>
	<%= check_box_tag :mmr %>MMR?
	<%= check_box_tag :wand %>WAND?
<% end %>
<br>
<br>

<table style="float:left" border="1" width="60%">
	<thead>
		<tr>
			<th>Created At</th>
			<th>Seed-Url</th>
			<th>Max-Depth</th>
			<th>Max-Pages</th>
			<th># of Retrieved</th>
			<th>Collection Id</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @collections.each do |collection| %>
			<tr>
				<td>
					<%= collection.created_at %>
				</td>
				<td>
					<%=  collection.seed_url %>
				</td>
				<td style="text-align: center;">
					<%=  collection.max_depth %>
				</td>
				<td style="text-align: center;">
					<%= collection.max_pages %>
				</td>
				<td style="text-align: center;">
					<%= collection.no_of_pages_retrieved %>
				</td>
				<td style="text-align: center;">
				<%= collection.collection_id %>
				</td>
				<td>
					<%= radio_button("selected_collection","collection_id",collection.id) %>
				</td>
			</tr>
		<% end %>
	</tbody>
	<%= button_to 'New Collection', new_collection_path(), :method => :get %>
</table>

app/views/index/new_collection.html.erb
<h2> New Collection </h2>

<%= form_for @collection, :url => save_collection_path(@collection) do |c| %>
	<table border="0" width="50%">
		<tr>
			<td>
				<%= c.label :seed_url %>:
			</td>
			<td>
				<%= c.text_field :seed_url %><br />
			</td>
		</tr>
		<tr>
			<td>
				<%= c.label :max_depth %>
			</td>
			<td>
				<%= c.number_field :max_depth %><br />	
			</td>
		</tr>
		<tr>
			<td>
				<%= c.label :max_pages %>
			</td>
			<td>
				<%= c.number_field :max_pages %><br />	
			</td>
		</tr>
	</table>
	<%= c.submit %>
<% end %>

app/views/index/search_query.html.erb
<h2> Results for '<%= @query %>'</h2>
<table style="float:left" border="0" width="60%">
	<% @results.each do |result| %>
		<tr><td>
		<%= link_to result, result, :target => "_blank" %>
		</td></tr>
	<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CustomWebSearchEngineServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>